### PR TITLE
Upgrade @rails/webpacker

### PR DESCRIPTION
**Pull request by jmhooper**
So that we use the latest and greatest

### CODE REVIEW

**Review by orenyk — COMMENTED** [review]
@jmhooper were you hoping to just merge this in and see if it works?

**Comment by NatashaJIbrahim** [comment]
@orenyk thank you for saying what I was thinking 😅 .

**Comment by jmhooper** [comment]
@NatashaJIbrahim @orenyk: Something like that. @julialeague and I tried getting this running in her sandbox. We made some progress but I don't think we are ready to merge quite yet. We've set up some time to continue on Monday.

**Comment by NatashaJIbrahim** [comment]
@jmhooper @julialeague 🙏🙏🙏 Thank you thank you thank you for digging in here.

**Comment by jmhooper** [comment]
After spending a couple hours fighting with @rails/webpacker we have determined the best move is probably to go straight to jsbundling. I'm going to close this and open a PR for jsbundling.

**Comment by NatashaJIbrahim** [comment]
@jmhooper would that involve upgrading to 7 and/or help with upgrading to 7? Just looking to download a little more context into my brain.

**Comment by jmhooper** [comment]
We don't need to upgrade to rails 7 use jsbundling. I believe moving away from @rails/webpacker will help with the 7 upgrade.

**Pull request closed without merging**
