### PR TITLE
Config name fixes for SLO

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by pkarman** [comment]
The `name_id_format` change was a regression from https://github.com/18F/identity-dashboard/commit/605d4832e2d1947737adbdf3c1030118d6b8d3c3#diff-4676c008b11a5480d73d4a6de01e45b9L33

I am working on a test specifically for the signature config.

**Comment by amoose** [comment]
Thank you for jumping on these issues, Peter. I'll review when the signature spec is complete!

**Comment by amoose** [comment]
Also, since the current nameID format is a simple config, let's add a simple spec to confirm that value.

**Comment by pkarman** [comment]
@amoose tests added, PTAL

**Comment by jessieay** [comment]
@pkarman looks like these needs a rebase.

**Comment by pkarman** [comment]
@jessieay rebased and codeclimate errors addressed.

**Comment by jessieay** [comment]
@pkarman looks like CC is still mad at you 😸

**Comment by pkarman** [comment]
@jessieay CC is perennially mad at me. :/

think I got the trick this time.

**Pull request merged**
