### PR TITLE
Add ability to set logo name when adding SP

### PR DESCRIPTION
**Pull request by jessieay**
**WHY**: Agencies can add logos!

When logo name is invalid:

screen shot 2017-03-30 at 11 56 40 am

When logo name is valid:

screen shot 2017-03-30 at 11 57 40 am

### CODE REVIEW

**Comment by jessieay** [comment]
cc @blacktm for input on UX for this

**Comment by blacktm** [comment]
Yea, I agree with you @nickbristow, "Logo" is probably fine. We'll have instructions/context both in our dev docs and in outreach emails to agencies.

**Comment by blacktm** [comment]
Other than that, I think this looks great. I didn't even think to preview the logo in the dashboard (duh) — great idea!

**Comment by jessieay** [comment]
@blacktm @nickbristow good call. Updated at 4f65318

Also updated the preview to show the generic logo svg if no logo is set so they will know what logo will show for them in the SP.

**Comment by blacktm** [comment]
Great, I think good to go then, unless @nickbristow has any last thoughts.

**Pull request merged**
